services:
  notes.api:
    image: notes.api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    
    
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgersql/data
          
          
volumes:
  postgres-data: